package TME5.HashDistante;

/**
* HashDistante/HashDistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashDistante.idl
* jeudi 17 mars 2016 18 h 12 CET
*/

public final class HashDistHolder implements org.omg.CORBA.portable.Streamable
{
  public HashDist value = null;

  public HashDistHolder ()
  {
  }

  public HashDistHolder (HashDist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HashDistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HashDistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HashDistHelper.type ();
  }

}
