package TME5.HashDistante;


/**
* HashDistante/HashDistHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashDistante.idl
* jeudi 17 mars 2016 18 h 12 CET
*/

abstract public class HashDistHelper
{
  private static String  _id = "IDL:HashDistante/HashDist:1.0";

  public static void insert (org.omg.CORBA.Any a, HashDist that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HashDist extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HashDistHelper.id (), "HashDist");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HashDist read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HashDistStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HashDist value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HashDist narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HashDist)
      return (HashDist)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _HashDistStub stub = new _HashDistStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static HashDist unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HashDist)
      return (HashDist)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _HashDistStub stub = new _HashDistStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
