package TME5.HashDistante;


/**
* HashDistante/HashDistOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashDistante.idl
* jeudi 17 mars 2016 18 h 12 CET
*/

public interface HashDistOperations 
{
  boolean containsKey (String key);
  org.omg.CORBA.Object get (String key);
  void put (String key, org.omg.CORBA.Object val);
} // interface HashDistOperations
