package TME5.HashDistante;


/**
* HashDistante/HashDist.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HashDistante.idl
* jeudi 17 mars 2016 18 h 12 CET
*/

public interface HashDist extends HashDistOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HashDist
