package TME6.cache;

/**
* cache/FileSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* jeudi 24 mars 2016 17 h 10 CET
*/

public final class FileSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public FileSystem value = null;

  public FileSystemHolder ()
  {
  }

  public FileSystemHolder (FileSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileSystemHelper.type ();
  }

}
