package TME6.cache;


/**
* cache/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* jeudi 24 mars 2016 17 h 10 CET
*/

public interface FileSystemOperations 
{
  boolean lire (String ref, org.omg.CORBA.StringHolder data) throws DoesNotExist, IOException;
  boolean ecrire (String ref, String data) throws IOException;
} // interface FileSystemOperations
