package TME6.cache;


/**
* cache/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* jeudi 24 mars 2016 17 h 10 CET
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
