package TME6.cache;

/**
* cache/IOExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* jeudi 24 mars 2016 17 h 10 CET
*/

public final class IOExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public IOException value = null;

  public IOExceptionHolder ()
  {
  }

  public IOExceptionHolder (IOException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IOExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IOExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IOExceptionHelper.type ();
  }

}
