/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


void
calcul_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  mulpar2_1_arg;
	void  *result_2;
	struct data  affiche_champs_1_arg;
	char * *result_3;
	struct bichaine  concat_1_arg;
	void  *result_4;
	char *plusum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCUL, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	mulpar2_1_arg = 2;
	result_1 = mulpar2_1(&mulpar2_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("La multiplication par 2 de %d donne: %d\n", mulpar2_1_arg, *result_1);
	
	affiche_champs_1_arg.c1 = 4;
	affiche_champs_1_arg.c2 = 'a';
	result_2 = affiche_champs_1(&affiche_champs_1_arg, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("La structure est composé de: %d et %c\n", affiche_champs_1_arg.c1, affiche_champs_1_arg.c2);
	
	strcpy(concat_1_arg.s1, "Hello");
	strcpy(concat_1_arg.s2, "World");
	result_3 = concat_1(&concat_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("La concaténation de %s et %s donne %s\n", concat_1_arg.s1, concat_1_arg.s2,*result_3);
	
	
	result_4 = plusum_1((void*)&plusum_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcul_1 (host);
exit (0);
}
