/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int c1;
	char c2;
};
typedef struct data data;

struct bichaine {
	char s1[80];
	char s2[80];
};
typedef struct bichaine bichaine;

#define CALCUL 0x2134567
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define mulpar2 1
extern  int * mulpar2_1(int *, CLIENT *);
extern  int * mulpar2_1_svc(int *, struct svc_req *);
#define affiche_champs 2
extern  void * affiche_champs_1(struct data *, CLIENT *);
extern  void * affiche_champs_1_svc(struct data *, struct svc_req *);
#define concat 3
extern  char ** concat_1(struct bichaine *, CLIENT *);
extern  char ** concat_1_svc(struct bichaine *, struct svc_req *);
#define plusum 4
extern  void * plusum_1(void *, CLIENT *);
extern  void * plusum_1_svc(void *, struct svc_req *);
extern int calcul_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mulpar2 1
extern  int * mulpar2_1();
extern  int * mulpar2_1_svc();
#define affiche_champs 2
extern  void * affiche_champs_1();
extern  void * affiche_champs_1_svc();
#define concat 3
extern  char ** concat_1();
extern  char ** concat_1_svc();
#define plusum 4
extern  void * plusum_1();
extern  void * plusum_1_svc();
extern int calcul_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_bichaine (XDR *, bichaine*);

#else /* K&R C */
extern bool_t xdr_data ();
extern bool_t xdr_bichaine ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
