package TME5.Calculatrice;


/**
* Calculatrice/CalculateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* jeudi 17 mars 2016 17 h 09 CET
*/

public interface CalculateurOperations 
{
  double add (double a, double b);
  double sub (double a, double b);
  double mult (double a, double b);
  double div (double a, double b);
} // interface CalculateurOperations
