package TME5.Calculatrice;


/**
* Calculatrice/Calculateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* jeudi 17 mars 2016 17 h 09 CET
*/

public interface Calculateur extends CalculateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculateur
