package TME5.Calculatrice;

/**
* Calculatrice/DivisionZeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* jeudi 17 mars 2016 17 h 09 CET
*/

public final class DivisionZeroHolder implements org.omg.CORBA.portable.Streamable
{
  public DivisionZero value = null;

  public DivisionZeroHolder ()
  {
  }

  public DivisionZeroHolder (DivisionZero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DivisionZeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DivisionZeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DivisionZeroHelper.type ();
  }

}
