package TME5.Calculatrice;


/**
* Calculatrice/DivisionZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* jeudi 17 mars 2016 17 h 09 CET
*/

public final class DivisionZero extends org.omg.CORBA.UserException
{
  public double dividande = (double)0;

  public DivisionZero ()
  {
    super(DivisionZeroHelper.id());
  } // ctor

  public DivisionZero (double _dividande)
  {
    super(DivisionZeroHelper.id());
    dividande = _dividande;
  } // ctor


  public DivisionZero (String $reason, double _dividande)
  {
    super(DivisionZeroHelper.id() + "  " + $reason);
    dividande = _dividande;
  } // ctor

} // class DivisionZero
